In [1]:
import pandas as pd
import os
import csv
import re
import cyrtranslit

In [2]:
path = "C:\\Users\\mace\\OneDrive - Zühlke Engineering AG\\Documents\\master-thesis-code\\raw data\\Potrošačka korpa\\extracted"
# we shall store all the file names in this list
filelist = []

for root, dirs, files in os.walk(path):
    for file in files:
        # append the file name to the list
        filelist.append(os.path.join(root, file))

for file in filelist:
    if 'prehramb' in str(file).lower():
        print(str(file).lower())
        filename=str(file).lower().split('\\')[-1]
        df=pd.read_csv(file,skiprows=5, error_bad_lines=False)
        break
        
def transliterate_serbian(col):
    return cyrtranslit.to_latin(col,'sr')

In [5]:
struktura_list=[a for a in filelist if 'prehramb' in str(file).lower()]

In [3]:
file=struktura_list.pop()
print(file)

In [ ]:
filename=str(file).lower().split('\\')[-1]
mesec=filename.replace('.csv','').strip().split(' ')[-2].lower()
godina=int(re.findall('\d+',filename)[0])
df=pd.read_csv(file,skiprows=3, error_bad_lines=False)
df.drop('1',axis=1,inplace=True)
df.head()
start=["Artikal",f"{mesec} 2000"]
column_names=[f"{mesec} {god}" for god in range(godina-8,godina+1)]
[start.append(e) for e in column_names]
df.columns=start
df['Artikal']=df['Artikal'].apply(transliterate_serbian)
pretty_path = "C:\\Users\\mace\\OneDrive - Zühlke Engineering AG\\Documents\\master-thesis-code\\raw data\\Potrošačka korpa\\extracted\\clean\\"
df.to_csv(f"{pretty_path}{filename}")

In [1491]:
df

,Artikal,novembar 2000,novembar 2003,novembar 2004,novembar 2005,novembar 2006,novembar 2007,novembar 2008,novembar 2009,novembar 2010,novembar 2011
0,"Jestivo ulje,rafinisano",166,195.000,251.000,210.000,289.000,305.000,278.000,328.000,256.000,290.000
1,"Šećer,kristal",187,289.000,335.000,313.000,328.000,492.000,548.000,515.000,453.000,356.000
2,Svinj. meso sa kostima,17,62.000,49.000,53.000,82.000,92.000,69.000,76.000,85.000,93.000
3,"Kravlje mleko, pasterizo.",285,518.000,519.000,570.000,592.000,580.000,585.000,603.000,577.000,569.000
4,Jogurt,97,322.000,326.000,338.000,364.000,375.000,406.000,391.000,405.000,414.000
5,Kafa pržena,12,49.000,46.000,41.000,43.000,53.000,55.000,44.000,45.000,41.000
6,Kisela voda*,228,655.000,719.000,502.000,627.000,770.000,713.000,803.000,869.000,952.000
7,Mlečna čokolada,11,26.000,30.000,29.000,32.000,39.000,41.000,35.000,38.000,38.000
8,Krompir,150,450.000,1.032,922.000,831.000,930.000,1.075,1.034,719.000,1.037
9,Sladak kupus,-,1.097,1.653,920.000,1.738,944.000,1.937,1.413,1.361,1.562
10,Limun,41,169.000,229.000,216.000,308.000,277.000,288.000,287.000,326.000,413.000
11,Kokošija jaja,610,2.741,2.388,2.436,3.399,3.595,2.841,3.276,3.610,3.310
12,Pšenič. brašno,245,442.000,444.000,444.000,829.000,736.000,645.000,723.000,693.000,654.000